#!/bin/sh
set -e

ENV_JS_PATH=/app/public/env.js

cat <<EOF > $ENV_JS_PATH
window.__ENV__ = {
  NODE_ENV: "${NODE_ENV}",
  NEXT_PUBLIC_API_BASE_URL: "${NEXT_PUBLIC_API_BASE_URL}",
  NEXT_PUBLIC_AUTH_URL: "${NEXT_PUBLIC_AUTH_URL}",
  NEXT_PUBLIC_BASE_WS_URL: "${NEXT_PUBLIC_BASE_WS_URL}",
  NEXT_PUBLIC_PLATFORM_BASE_DOMAIN: "${NEXT_PUBLIC_PLATFORM_BASE_DOMAIN}",
  NEXT_PUBLIC_MAIN_TENANT_KEY: "${NEXT_PUBLIC_MAIN_TENANT_KEY}",
  NEXT_PUBLIC_SUPPORT_EMAIL: "${NEXT_PUBLIC_SUPPORT_EMAIL}",
};
EOF

echo "env.js generated at $ENV_JS_PATH"

exec "$@"
