"use client"

import { useState, useEffect, useRef } from "react"
import Image from "next/image"
import { useRouter } from "next/navigation"
import { SidebarLearner } from "@/components/platform/sidebar-learner"
import { Header } from "@/components/platform/header"
import { PlatformFooter } from "@/components/platform/platform-footer"
import { Plus, Mic, ArrowUp, Square, RotateCw, ArrowLeft, Bold, Italic, Link as LinkIcon, List, ListOrdered, Upload, Sparkles, FileImage, X, Check, Copy, Volume2, Reply, Building2 } from "lucide-react"
import { cn } from "@/lib/utils"
import { JumpstartTemplates } from "@/components/jumpstart-templates"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { AddSourcesDialog, type SelectedSource } from "@/components/chat-input/add-sources-dialog"
import { ChatInputForm } from "@/components/chat-input-form"
import { LoadingMessage } from "@/components/loading-message"
import { TooltipFlowbite, TooltipProvider } from "@/components/ui/tooltip-flowbite"
import { CreatingCourseProgress } from "@/components/creating-course-progress"
import { toast } from "sonner"

interface ChatMessage {
  id: string
  role: "user" | "assistant"
  content: string
  /** When true, show a "Start course setup" button under this assistant message */
  createCourseCta?: boolean
  /** User's text used to prefill course form when CTA is clicked */
  courseNameForCta?: string
}

function formatAssistantMessage(content: string): string {
  let formatted = content.replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold text-slate-700">$1</strong>')
  formatted = formatted.replace(/_(.*?)_/g, '<span class="underline">$1</span>')
  formatted = formatted.replace(/^• (.*)$/gm, '<li class="ml-4 mb-1">$1</li>')
  formatted = formatted.replace(
    /^(\d+)\. (.*)$/gm,
    '<li class="ml-4 mb-1"><span class="inline-flex items-center justify-center w-5 h-5 rounded bg-[#00A3EC] text-white text-xs font-medium mr-1.5">$1</span> $2</li>',
  )
  formatted = formatted.replace(/(<li.*?<\/li>\n?)+/g, '<ul class="list-disc list-inside my-2 space-y-1">$&</ul>')
  formatted = formatted.replace(/\n/g, "<br/>")
  formatted = formatted.replace(/✅/g, '<span class="text-green-600 inline-flex">✓</span>')
  return formatted
}

/** Detect if user is asking to create a new course (e.g. "create a course", "new course") */
function isCreateCourseIntent(text: string): boolean {
  const t = text.trim().toLowerCase()
  return (
    /\b(create|make|start|build)\s+(a\s+)?(new\s+)?course\b/.test(t) ||
    /\bnew\s+course\b/.test(t) ||
    /\bcourse\s+creation\b/.test(t)
  )
}

declare global {
  interface Window {
    SpeechRecognition: new () => any
    webkitSpeechRecognition: new () => any
  }
}

export default function HomePage() {
  const [inputValue, setInputValue] = useState("")
  const [isListening, setIsListening] = useState(false)
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [showCourseForm, setShowCourseForm] = useState(false)
  const [formStep, setFormStep] = useState<1 | 2>(1)
  const [isRegenerating, setIsRegenerating] = useState(false)
  const [isRegeneratingDescription, setIsRegeneratingDescription] = useState(false)
  const [isAutoGeneratingDescriptions, setIsAutoGeneratingDescriptions] = useState(false)
  const [hasAutoGeneratedDescriptions, setHasAutoGeneratedDescriptions] = useState(false)
  const [isAddSourcesDialogOpen, setIsAddSourcesDialogOpen] = useState(false)
  const [selectedAttachments, setSelectedAttachments] = useState<SelectedSource[]>([])
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [isAssistantTyping, setIsAssistantTyping] = useState(false)
  const [inputBarBottom, setInputBarBottom] = useState(56)
  const [copiedMessageId, setCopiedMessageId] = useState<string | null>(null)
  const [replyingTo, setReplyingTo] = useState<{ id: string; content: string } | null>(null)
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const [isCreatingCourse, setIsCreatingCourse] = useState(false)
  const [creationStep, setCreationStep] = useState<1 | 2 | 3>(1)
  const [creationProgress, setCreationProgress] = useState(0)
  const [completedActions, setCompletedActions] = useState<{ label: string; time: string }[]>([])
  const [showAcademyChoiceDialog, setShowAcademyChoiceDialog] = useState(false)
  const [academyCreationPhase, setAcademyCreationPhase] = useState<"form" | "creating" | "preview">("form")
  const [createAcademyForm, setCreateAcademyForm] = useState<{
    imageFile: File | null
    imagePreview: string | null
    title: string
    subtitle: string
    membershipPricing: string
  }>({ imageFile: null, imagePreview: null, title: "", subtitle: "", membershipPricing: "" })
  const pendingCourseEditRef = useRef<{ courseId: string; courseName: string } | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const recognitionRef = useRef<any>(null)
  const userRequestedStopRef = useRef(false)
  const accumulatedTranscriptRef = useRef("")
  const restartTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const silenceTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const [courseForm, setCourseForm] = useState({
    courseName: "",
    organization: "test_admin",
    courseNumber: "",
    courseRun: "",
  })
  const [courseDetailsForm, setCourseDetailsForm] = useState({
    displayName: "",
    startDate: "",
    endDate: "",
    enrollmentStartDate: "",
    enrollmentEndDate: "",
    description: "",
    shortDescription: "",
    imageTab: "upload" as "upload" | "generate",
    imageDescriptionPrompt: "",
    isGeneratingImage: false,
    generatedImageUrl: null as string | null,
    uploadedImageUrl: null as string | null,
  })
  const router = useRouter()

  const isLoggedIn = true

  // Cleanup speech recognition on unmount
  useEffect(() => {
    return () => {
      userRequestedStopRef.current = true
      if (silenceTimeoutRef.current) {
        clearTimeout(silenceTimeoutRef.current)
        silenceTimeoutRef.current = null
      }
      if (restartTimeoutRef.current) {
        clearTimeout(restartTimeoutRef.current)
        restartTimeoutRef.current = null
      }
      if (recognitionRef.current) {
        try {
          recognitionRef.current.stop()
        } catch (_) {}
        recognitionRef.current = null
      }
      setIsListening(false)
    }
  }, [])

  // Stop listening when user clicks anywhere else on the page (not inside prompt area)
  useEffect(() => {
    if (!isListening) return
    const stopOnClick = (e: MouseEvent | TouchEvent) => {
      const node = e.target as Node | null
      const el = node?.nodeType === Node.ELEMENT_NODE ? (node as Element) : (node?.parentElement ?? null)
      if (el?.closest?.("[data-prompt-area]")) return
      stopDictation()
    }
    document.addEventListener("mousedown", stopOnClick)
    document.addEventListener("touchstart", stopOnClick)
    return () => {
      document.removeEventListener("mousedown", stopOnClick)
      document.removeEventListener("touchstart", stopOnClick)
    }
  }, [isListening])

  const hasChatMessages = messages.length > 0
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }
  useEffect(() => {
    scrollToBottom()
  }, [messages, isAssistantTyping])

  // Position fixed input bar above keyboard on mobile when keyboard is visible
  useEffect(() => {
    if (typeof window === "undefined" || !window.visualViewport) return
    const vv = window.visualViewport
    const update = () => {
      const bottom =
        vv.height > 0 && vv.height < window.innerHeight - 80
          ? window.innerHeight - vv.height
          : 56
      setInputBarBottom(bottom)
    }
    update()
    vv.addEventListener("resize", update)
    vv.addEventListener("scroll", update)
    return () => {
      vv.removeEventListener("resize", update)
      vv.removeEventListener("scroll", update)
    }
  }, [])

  const stopDictation = () => {
    userRequestedStopRef.current = true
    if (silenceTimeoutRef.current) {
      clearTimeout(silenceTimeoutRef.current)
      silenceTimeoutRef.current = null
    }
    if (restartTimeoutRef.current) {
      clearTimeout(restartTimeoutRef.current)
      restartTimeoutRef.current = null
    }
    if (recognitionRef.current) {
      try {
        recognitionRef.current.stop()
      } catch (_) {}
      recognitionRef.current = null
    }
    setIsListening(false)
  }

  const startRecognition = () => {
    const SpeechRecognition = typeof window !== "undefined" && (window.SpeechRecognition || window.webkitSpeechRecognition)
    if (!SpeechRecognition) return null
    const recognition = new SpeechRecognition()
    recognition.continuous = true
    recognition.interimResults = true
    recognition.lang = "en-US"
    recognition.onresult = (event: any) => {
      let interim = ""
      let hadFinal = false
      for (let i = event.resultIndex; i < event.results.length; i++) {
        const t = event.results[i][0].transcript
        if (event.results[i].isFinal) {
          accumulatedTranscriptRef.current += t
          hadFinal = true
        } else {
          interim += t
        }
      }
      setInputValue(accumulatedTranscriptRef.current + interim)
      if (hadFinal) {
        if (silenceTimeoutRef.current) clearTimeout(silenceTimeoutRef.current)
        silenceTimeoutRef.current = setTimeout(() => stopDictation(), 2000)
      }
    }
    recognition.onerror = (event: any) => {
      const err = event?.error
      if (err === "not-allowed" || err === "no-speech") {
        userRequestedStopRef.current = true
      }
      if (recognitionRef.current === recognition) {
        recognitionRef.current = null
      }
      setIsListening(false)
    }
    recognition.onend = () => {
      if (userRequestedStopRef.current) {
        recognitionRef.current = null
        setIsListening(false)
        return
      }
      if (recognitionRef.current !== recognition) return
      recognitionRef.current = null
      restartTimeoutRef.current = setTimeout(() => {
        restartTimeoutRef.current = null
        if (userRequestedStopRef.current) {
          setIsListening(false)
          return
        }
        const next = startRecognition()
        if (next) {
          try {
            next.start()
            recognitionRef.current = next
          } catch (_) {
            setIsListening(false)
          }
        } else {
          setIsListening(false)
        }
      }, 80)
    }
    return recognition
  }

  const handleDictationClick = () => {
    if (isListening) {
      stopDictation()
      return
    }

    const SpeechRecognition = typeof window !== "undefined" && (window.SpeechRecognition || window.webkitSpeechRecognition)
    if (!SpeechRecognition) {
      if (typeof window !== "undefined") {
        alert("Your browser does not support speech recognition. Please try Chrome or Edge.")
      }
      return
    }

    userRequestedStopRef.current = false
    accumulatedTranscriptRef.current = inputValue
    setIsListening(true)

    const recognition = startRecognition()
    if (!recognition) return
    try {
      recognition.start()
      recognitionRef.current = recognition
    } catch (_) {
      recognitionRef.current = null
      setIsListening(false)
    }
  }

  const handleSubmit = () => {
    const text = inputValue.trim()
    if (!text) return

    // Always show chat list view: add user message first
    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: "user",
      content: text,
    }
    setMessages((prev) => [...prev, userMessage])
    setInputValue("")
    setReplyingTo(null)
    setIsAssistantTyping(true)

    if (isCreateCourseIntent(text)) {
      // User asked to create a course → show chat response with CTA to create course
      const assistantMessage: ChatMessage = {
        id: `assistant-${Date.now()}`,
        role: "assistant",
        content:
          "I'd be happy to help you **create a new course**. Tell me the topic or title you have in mind, and I'll guide you through setting it up. Use the button below to open the course creation form and get started.",
        createCourseCta: true,
        courseNameForCta: text,
      }
      setTimeout(() => {
        setMessages((prev) => [...prev, assistantMessage])
        setIsAssistantTyping(false)
      }, 800)
      return
    }

    // Other messages: generic assistant reply
    const defaultAssistantReply = `Thanks for your message. I can help you **create a new course** or answer questions about course design and content. Just say "create a course" or describe what you'd like to build, and I'll guide you through it.`
    setTimeout(() => {
      const assistantMessage: ChatMessage = {
        id: `assistant-${Date.now()}`,
        role: "assistant",
        content: defaultAssistantReply,
      }
      setMessages((prev) => [...prev, assistantMessage])
      setIsAssistantTyping(false)
    }, 800)
  }

  /** Open course creation form with optional prefill from chat CTA */
  const openCreateCourseForm = (courseNameFromUser?: string) => {
    const generatedCourseName = (courseNameFromUser || "").trim() || "New course"
    const courseNumber = generatedCourseName
      .split(" ")
      .map((word) => word[0]?.toUpperCase() || "")
      .join("")
      .slice(0, 3)
    const now = new Date()
    const courseRun = `${now.getFullYear()}_${String(now.getMonth() + 1).padStart(2, "0")}`

    setCourseForm({
      courseName: generatedCourseName,
      organization: "test_admin",
      courseNumber: courseNumber,
      courseRun: courseRun,
    })
    setCourseDetailsForm((prev) => ({
      ...prev,
      displayName: generatedCourseName,
      description: `The ${generatedCourseName} course is designed to provide comprehensive learning on this topic. This course covers fundamental concepts and explores practical applications.`,
      shortDescription: `The ${generatedCourseName} course is designed to equip professionals with the knowledge and tools needed.`,
      imageDescriptionPrompt: generatedCourseName,
    }))
    setShowCourseForm(true)
    setFormStep(2)
  }

  const handleRegenerate = () => {
    setIsRegenerating(true)
    setTimeout(() => {
      const generatedCourseName = inputValue.trim()
      setCourseForm((prev) => ({
        ...prev,
        courseName: generatedCourseName,
      }))
      setIsRegenerating(false)
    }, 1000)
  }

  const handleRegenerateDisplayName = () => {
    setIsRegenerating(true)
    setTimeout(() => {
      const generatedName = courseForm.courseName || inputValue.trim()
      setCourseDetailsForm((prev) => ({
        ...prev,
        displayName: generatedName,
      }))
      setIsRegenerating(false)
    }, 1000)
  }

  const handleRegenerateDescription = () => {
    setIsRegeneratingDescription(true)
    setTimeout(() => {
      const generatedDescription = `The ${courseForm.courseName || courseDetailsForm.displayName} course is designed to provide comprehensive learning on this topic. This course covers fundamental concepts and explores practical applications.`
      setCourseDetailsForm((prev) => ({
        ...prev,
        description: generatedDescription,
      }))
      setIsRegeneratingDescription(false)
    }, 1000)
  }

  const handleGenerateImage = () => {
    if (!courseDetailsForm.imageDescriptionPrompt.trim()) {
      return
    }
    setCourseDetailsForm((prev) => ({ ...prev, isGeneratingImage: true }))
    // Simulate image generation (replace with actual API call)
    setTimeout(() => {
      // In a real app, this would be the URL from the API response
      const mockImageUrl = `https://picsum.photos/800/600?random=${Date.now()}`
      setCourseDetailsForm((prev) => ({
        ...prev,
        isGeneratingImage: false,
        generatedImageUrl: mockImageUrl,
      }))
    }, 3000) // 3 second animation
  }

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onloadend = () => {
        setCourseDetailsForm((prev) => ({
          ...prev,
          uploadedImageUrl: reader.result as string,
        }))
      }
      reader.readAsDataURL(file)
    }
  }

  const handleFileInputTrigger = () => {
    fileInputRef.current?.click()
  }

  const handleBack = () => {
    setShowCourseForm(false)
    setInputValue("")
  }

  const handleNext = () => {
    if (formStep === 1) {
      setFormStep(2)
    }
  }

  // Auto-generate descriptions when step 2 loads
  useEffect(() => {
    if (formStep === 2 && !hasAutoGeneratedDescriptions && !courseDetailsForm.description && !courseDetailsForm.shortDescription) {
      setIsAutoGeneratingDescriptions(true)
      setHasAutoGeneratedDescriptions(true)
      // Simulate AI generation with a delay
      setTimeout(() => {
        const courseName = courseForm.courseName || courseDetailsForm.displayName || "this course"
        const generatedDescription = `The ${courseName} course is designed to provide comprehensive learning on this topic. This course covers fundamental concepts, explores practical applications, and equips learners with the knowledge and skills needed to excel. Through interactive lessons, hands-on exercises, and real-world examples, students will gain a deep understanding of the subject matter and be prepared to apply their learning in professional settings.`
        const generatedShortDescription = `The ${courseName} course is designed to equip professionals with the knowledge and tools needed to succeed.`
        
        setCourseDetailsForm((prev) => ({
          ...prev,
          description: generatedDescription,
          shortDescription: generatedShortDescription,
        }))
        setIsAutoGeneratingDescriptions(false)
      }, 2000) // 2 second generation animation
    }
  }, [formStep, hasAutoGeneratedDescriptions, courseDetailsForm.description, courseDetailsForm.shortDescription, courseForm.courseName, courseDetailsForm.displayName])

  const formatTime = () => {
    const now = new Date()
    return now.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", second: "2-digit", hour12: true })
  }

  const handleCreateCourse = () => {
    console.log("Create course with:", { ...courseForm, ...courseDetailsForm })
    setIsCreatingCourse(true)
    setCreationStep(1)
    setCreationProgress(0)
    setCompletedActions([])

    const courseId = `course-v1:${(courseForm.courseNumber || "ACI")}+UTA+${courseForm.courseRun || "2026_03"}`

    setCreationProgress(20)
    setTimeout(() => {
      setCompletedActions((prev) => [
        ...prev,
        { label: `Step 1: Created course - ID: ${courseId}`, time: formatTime() },
      ])
      setCreationStep(2)
      setCreationProgress(45)
    }, 1500)

    setTimeout(() => {
      setCompletedActions((prev) => [
        ...prev,
        { label: "Step 2: Updated course description", time: formatTime() },
      ])
      setCreationStep(3)
      setCreationProgress(70)
    }, 3500)

    setTimeout(() => {
      setCreationProgress(100)
      setCompletedActions((prev) => [
        ...prev,
        { label: "Step 3: Generated course content", time: formatTime() },
      ])
      const courseId = `course-v1:${(courseForm.courseNumber || "ACI")}+UTA+${courseForm.courseRun || "2026_03"}`
      const courseName = courseForm.courseName || courseDetailsForm.displayName || "New course"
      pendingCourseEditRef.current = { courseId, courseName }
      setTimeout(() => {
        const hasAcademy = typeof window !== "undefined" && localStorage.getItem("hasAcademy") === "1"
        if (hasAcademy) {
          const pending = pendingCourseEditRef.current
          if (pending) {
            router.push(`/course/${pending.courseId}/edit?name=${encodeURIComponent(pending.courseName)}`)
          }
        } else {
          setShowAcademyChoiceDialog(true)
        }
      }, 800)
    }, 7000)
  }

  const handleTemplateClick = (template: string) => {
    setInputValue(template)
  }

  const handleRemoveAcademyImage = () => {
    if (createAcademyForm.imagePreview) URL.revokeObjectURL(createAcademyForm.imagePreview)
    setCreateAcademyForm((prev) => ({ ...prev, imageFile: null, imagePreview: null }))
  }

  const successToastStyle = {
    duration: 3000,
    style: {
      background: "linear-gradient(135deg, #00A3EC 0%, #6988FF 100%)",
      color: "white",
      border: "none",
      borderRadius: "12px",
      padding: "14px 18px",
      fontSize: "15px",
      fontWeight: "600",
      boxShadow: "0 4px 12px rgba(0, 163, 236, 0.3)",
      WebkitFontSmoothing: "antialiased",
      MozOsxFontSmoothing: "grayscale",
      WebkitTapHighlightColor: "transparent",
      touchAction: "manipulation",
    },
    className: "toast-success",
  } as const

  return (
    <div className="h-screen-dvh overflow-y-auto bg-background">
      {/* Sidebar */}
      <SidebarLearner
        isCollapsed={sidebarCollapsed}
        onToggleCollapse={() => setSidebarCollapsed(!sidebarCollapsed)}
        isMobileOpen={mobileMenuOpen}
        onMobileClose={() => setMobileMenuOpen(false)}
        showAdminButtons={true}
        isLoggedIn={isLoggedIn}
      />

      {/* Main Content Area */}
      <div
        className={cn(
          "flex flex-col min-h-screen-dvh transition-all duration-300",
          sidebarCollapsed ? "md:ml-16" : "md:ml-64",
        )}
      >
        {/* Header - fixed at top, does not scroll */}
        <Header
          onMobileMenuToggle={() => setMobileMenuOpen(true)}
          isLoggedIn={isLoggedIn}
          showLogo={true}
          showBackButton={true}
          showModelSelector={true}
          sidebarCollapsed={sidebarCollapsed}
        />

        <div className="flex flex-1 min-h-0 min-w-0">
          <main className="flex-1 flex flex-col min-h-0 min-w-0 transition-all duration-300 pb-[200px] md:pb-[200px] overflow-x-hidden">
          <div className="flex flex-1 min-h-0 min-w-0">
            <div
              className={cn(
                "flex-1 min-h-0 min-w-0 flex pt-8 pb-8 w-full max-w-full",
                hasChatMessages ? "px-3 sm:px-4 items-start justify-center" : "px-4 sm:px-6 sm:pl-8 sm:pr-8 md:pr-20 items-start justify-center"
              )}
            >
          <div className={cn("w-full min-w-0", hasChatMessages ? "max-w-3xl mx-auto" : "max-w-6xl")}>
            {isCreatingCourse ? (
              <>
                <CreatingCourseProgress
                  courseName={courseDetailsForm.displayName || courseForm.courseName || "New course"}
                  creationStep={creationStep}
                  creationProgress={creationProgress}
                  completedActions={completedActions}
                  courseCreated={showAcademyChoiceDialog}
                />
                {showAcademyChoiceDialog && (
                  <div className="mt-8 w-full min-w-0 px-1">
                    <div className="w-full rounded-lg border border-gray-200 bg-white overflow-hidden flex flex-col shadow-sm">
                      {academyCreationPhase === "form" ? (
                        <>
                          <div className="flex-shrink-0 p-4 sm:p-6 pb-0 sm:pb-4 border-b border-gray-100">
                            <div className="flex items-start gap-3">
                              <div className="flex-shrink-0 w-10 h-10 rounded-full bg-[#eff6ff] border border-[#bfdbfe] flex items-center justify-center">
                                <Check className="w-5 h-5 text-blue-600" strokeWidth={2.5} />
                              </div>
                              <div className="min-w-0">
                                <h2 className="text-lg sm:text-xl font-semibold text-[var(--sidebar-foreground)]">
                                  Your course has been generated successfully.
                                </h2>
                                <p className="text-sm text-gray-600 mt-1">
                                  Set up your academy below or skip to continue editing your course.
                                </p>
                              </div>
                            </div>
                          </div>
                          <div className="flex-1 min-h-0 overflow-y-auto px-4 sm:px-6">
                            <div className="flex flex-col items-center pt-4 py-3 pb-0">
                              <input
                                id="academy-image-home"
                                type="file"
                                accept="image/png,image/jpeg,image/jpg,image/webp"
                                className="sr-only"
                                onChange={(e) => {
                                  const file = e.target.files?.[0]
                                  if (file) {
                                    const preview = URL.createObjectURL(file)
                                    setCreateAcademyForm((prev) => ({
                                      ...prev,
                                      imageFile: file,
                                      imagePreview: preview,
                                    }))
                                  }
                                  e.currentTarget.value = ""
                                }}
                              />
                              <div className="relative w-24 h-24 rounded-full overflow-hidden border border-gray-200 bg-gray-100 flex-shrink-0">
                                {createAcademyForm.imagePreview ? (
                                  <Image
                                    src={createAcademyForm.imagePreview}
                                    alt="Academy logo"
                                    fill
                                    className="object-cover"
                                  />
                                ) : (
                                  <div className="w-full h-full flex items-center justify-center text-gray-400">
                                    <Building2 className="w-10 h-10" strokeWidth={1.25} />
                                  </div>
                                )}
                              </div>
                              <button
                                type="button"
                                onClick={() => document.getElementById("academy-image-home")?.click()}
                                className="mt-3 text-sm font-medium text-[#0095F6] hover:text-[#00376B] underline underline-offset-1"
                              >
                                Edit Logo
                              </button>
                              {createAcademyForm.imagePreview && (
                                <button
                                  type="button"
                                  onClick={handleRemoveAcademyImage}
                                  className="mt-1 text-xs text-gray-500 hover:text-red-600"
                                >
                                  Remove photo
                                </button>
                              )}
                            </div>
                            <div className="space-y-4 py-3 pb-4 sm:space-y-5">
                              <div className="space-y-1.5">
                                <Label htmlFor="academy-title-home" className="text-xs font-normal text-gray-500 sm:text-sm">
                                  Name
                                </Label>
                                <Input
                                  id="academy-title-home"
                                  placeholder="e.g. Academy name"
                                  value={createAcademyForm.title}
                                  onChange={(e) =>
                                    setCreateAcademyForm((prev) => ({ ...prev, title: e.target.value }))
                                  }
                                  className="w-full h-11 rounded-lg border-gray-200 bg-white text-base font-normal text-[var(--sidebar-foreground)] placeholder:font-normal placeholder:text-gray-400 placeholder:text-sm sm:placeholder:text-base focus-visible:ring-1 focus-visible:ring-gray-300"
                                />
                              </div>
                              <div className="space-y-1.5">
                                <Label htmlFor="academy-subtitle-home" className="text-xs font-normal text-gray-500 sm:text-sm">
                                  Short description
                                </Label>
                                <div className="relative">
                                  <Textarea
                                    id="academy-subtitle-home"
                                    placeholder="e.g. Learn from industry experts"
                                    value={createAcademyForm.subtitle}
                                    rows={2}
                                    onChange={(e) => {
                                      const text = e.target.value
                                      const words = text.trim().split(/\s+/).filter(Boolean)
                                      if (words.length <= 20) {
                                        setCreateAcademyForm((prev) => ({ ...prev, subtitle: text }))
                                      } else {
                                        const truncated = words.slice(0, 20).join(" ")
                                        setCreateAcademyForm((prev) => ({ ...prev, subtitle: truncated }))
                                      }
                                    }}
                                    className="w-full min-h-[60px] max-h-[60px] rounded-lg border-gray-200 bg-white text-base font-normal text-[var(--sidebar-foreground)] placeholder:font-normal placeholder:text-gray-400 placeholder:text-sm sm:placeholder:text-base focus-visible:ring-1 focus-visible:ring-gray-300 pr-16 resize-none overflow-y-auto"
                                  />
                                  <span className="absolute bottom-2 right-3 text-[11px] font-normal text-gray-400 sm:text-xs">
                                    {createAcademyForm.subtitle.trim().split(/\s+/).filter(Boolean).length} / 20 words
                                  </span>
                                </div>
                              </div>
                              <div className="space-y-1.5">
                                <Label htmlFor="academy-pricing-home" className="text-xs font-normal text-gray-500 sm:text-sm">
                                  Membership price
                                </Label>
                                <Input
                                  id="academy-pricing-home"
                                  type="text"
                                  inputMode="decimal"
                                  placeholder="e.g. $9.99"
                                  value={createAcademyForm.membershipPricing}
                                  onChange={(e) => {
                                    const v = e.target.value.replace(/[^0-9.]/g, "")
                                    const parts = v.split(".")
                                    const filtered = parts.length > 2 ? parts[0] + "." + parts.slice(1).join("") : v
                                    setCreateAcademyForm((prev) => ({ ...prev, membershipPricing: filtered }))
                                  }}
                                  className="w-full h-11 rounded-lg border-gray-200 bg-white text-base font-normal text-[var(--sidebar-foreground)] placeholder:font-normal placeholder:text-gray-400 placeholder:text-sm sm:placeholder:text-base focus-visible:ring-1 focus-visible:ring-gray-300"
                                />
                              </div>
                            </div>
                          </div>
                          <div className="flex-shrink-0 flex flex-col-reverse sm:flex-row sm:justify-end gap-2 px-4 sm:px-6 py-4 border-t border-gray-100">
                            <Button
                              variant="outline"
                              onClick={() => {
                                const pending = pendingCourseEditRef.current
                                if (pending) {
                                  try {
                                    localStorage.setItem("hasAcademy", "0")
                                  } catch (_) {}
                                  pendingCourseEditRef.current = null
                                  router.push(`/course/${pending.courseId}/edit?name=${encodeURIComponent(pending.courseName)}`)
                                  // Don't reset state — avoids flashing home view before navigation completes
                                }
                              }}
                              className="px-4 py-2 text-sm font-medium border-gray-200 text-gray-700 hover:bg-gray-50 rounded-lg"
                            >
                              Skip
                            </Button>
                            <Button
                              onClick={async () => {
                                if (!createAcademyForm.title.trim()) {
                                  toast.error("Please enter a title for the academy.")
                                  return
                                }
                                let imageDataUrl: string | undefined
                                if (createAcademyForm.imageFile) {
                                  try {
                                    imageDataUrl = await new Promise<string>((resolve, reject) => {
                                      const r = new FileReader()
                                      r.onload = () => resolve(r.result as string)
                                      r.onerror = reject
                                      r.readAsDataURL(createAcademyForm.imageFile!)
                                    })
                                  } catch (_) {}
                                }
                                try {
                                  localStorage.setItem("hasAcademy", "1")
                                  localStorage.setItem(
                                    "academyDetails",
                                    JSON.stringify({
                                      title: createAcademyForm.title,
                                      subtitle: createAcademyForm.subtitle,
                                      membershipPricing: createAcademyForm.membershipPricing,
                                      ...(imageDataUrl && { imageDataUrl }),
                                    })
                                  )
                                } catch (_) {}
                                setAcademyCreationPhase("creating")
                                setTimeout(() => setAcademyCreationPhase("preview"), 2000)
                              }}
                              className="px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90 rounded-lg"
                            >
                              Create Academy
                            </Button>
                          </div>
                        </>
                      ) : academyCreationPhase === "creating" ? (
                        <div className="py-8 flex flex-col items-center justify-center text-center">
                          <div className="w-14 h-14 rounded-full border-4 border-[#00A3EC]/30 border-t-[#00A3EC] animate-spin mb-4" />
                          <h2 className="text-xl font-semibold text-[var(--sidebar-foreground)] mb-1">
                            Academy getting created...
                          </h2>
                          <p className="text-sm text-gray-600">Setting up your academy. This will only take a moment.</p>
                        </div>
                      ) : (
                        /* preview */
                        <div className="space-y-6">
                          <h2 className="text-xl font-semibold text-[var(--sidebar-foreground)] mb-1">
                            Your academy is ready
                          </h2>
                          <p className="text-sm text-gray-600 mb-4">
                            Here’s how your academy looks:
                          </p>
                          <div
                            className="rounded-2xl border border-gray-200/80 overflow-hidden bg-white max-w-md shadow-lg"
                            style={{ boxShadow: "0 8px 30px rgba(0,163,236,0.08), 0 2px 8px rgba(0,0,0,0.04)" }}
                          >
                            <div
                              className="px-6 pt-6 pb-5 bg-gradient-to-br from-[#E8F7FE] via-[#EEF4FF] to-[#EEF0FF]"
                              style={{ minHeight: "120px" }}
                            >
                              <div className="flex items-start gap-4">
                                {createAcademyForm.imagePreview ? (
                                  <div className="relative w-14 h-14 sm:w-16 sm:h-16 rounded-xl overflow-hidden border border-white/60 bg-white flex-shrink-0 shadow-sm">
                                    <Image
                                      src={createAcademyForm.imagePreview}
                                      alt="Academy logo"
                                      fill
                                      className="object-cover"
                                    />
                                  </div>
                                ) : (
                                  <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-xl bg-white/90 border border-white/60 flex items-center justify-center flex-shrink-0 shadow-sm">
                                    <span className="text-xl sm:text-2xl font-bold bg-gradient-to-r from-[#00A3EC] to-[#6988FF] bg-clip-text text-transparent">
                                      {createAcademyForm.title?.charAt(0) || "A"}
                                    </span>
                                  </div>
                                )}
                                <div className="min-w-0 flex-1 pt-0.5">
                                  <p className="text-xs font-medium uppercase tracking-wider text-[#00A3EC]/80 mb-1">Academy</p>
                                  <h3 className="text-lg font-semibold text-[var(--sidebar-foreground)] leading-tight break-words">
                                    {createAcademyForm.title || "My Academy"}
                                  </h3>
                                  {createAcademyForm.subtitle ? (
                                    <p className="text-sm text-gray-600 mt-2 line-clamp-2 leading-snug">{createAcademyForm.subtitle}</p>
                                  ) : null}
                                </div>
                              </div>
                            </div>
                            {createAcademyForm.membershipPricing ? (
                              <div className="px-6 py-3 bg-gray-50/80 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-sm text-gray-500">Membership</span>
                                <span className="text-sm font-semibold text-[#00A3EC]">${createAcademyForm.membershipPricing}<span className="font-normal text-gray-500">/month</span></span>
                              </div>
                            ) : null}
                          </div>
                          <div className="flex justify-start">
                            <Button
                              onClick={() => {
                                const pending = pendingCourseEditRef.current
                                if (pending) {
                                  pendingCourseEditRef.current = null
                                  router.push(`/course/${pending.courseId}/edit?name=${encodeURIComponent(pending.courseName)}`)
                                  // Don't reset state here — avoids flashing home view before navigation completes
                                }
                              }}
                              className="w-full sm:w-auto px-6 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90"
                            >
                              Continue editing the course
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </>
            ) : !showCourseForm ? (
              (() => {
                if (hasChatMessages) {
                  return (
              <div className="w-full pt-0 py-4 sm:py-6 pb-6 min-w-0 flex-1 min-h-0 overflow-y-auto scrollbar-hide">
                  {messages.map((msg) =>
                    msg.role === "user" ? (
                      <div key={msg.id} className="flex justify-end mb-4">
                        <div className="rounded-xl px-4 py-2.5 max-w-[85%] sm:max-w-[75%] bg-gray-100">
                          <p className="text-base sm:text-sm text-slate-800">{msg.content}</p>
                        </div>
                      </div>
                    ) : (
                      <div key={msg.id} className="mb-6">
                        <div
                          className="text-base sm:text-sm leading-relaxed prose sm:prose-sm max-w-none pb-2"
                          style={{ color: "rgb(113,121,133)" }}
                          dangerouslySetInnerHTML={{ __html: formatAssistantMessage(msg.content) }}
                        />
                        {msg.createCourseCta && (
                          <div className="mt-3 p-4 rounded-xl border-2 border-[#00A3EC]/20 bg-gradient-to-br from-[#F0F9FF] to-[#EEF0FF]">
                            <p className="text-sm text-[#4E5460] mb-3">
                              Click to start creating your course. We&apos;ll open the setup form and use your idea to get you started.
                            </p>
                            <Button
                              onClick={() => openCreateCourseForm(msg.courseNameForCta)}
                              className="bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90 text-white rounded-lg px-4 py-2 text-sm font-medium"
                            >
                              Start course setup
                            </Button>
                          </div>
                        )}
                        <div className="flex items-center gap-0.5 mt-1.5 pt-1 text-gray-400">
                          <TooltipFlowbite content={copiedMessageId === msg.id ? "Copied" : "Copy"} position="top">
                            <button
                              type="button"
                              className="p-1.5 hover:bg-gray-100 hover:text-gray-600 rounded-md transition-colors"
                              aria-label={copiedMessageId === msg.id ? "Copied" : "Copy"}
                              onClick={async () => {
                                try {
                                  await navigator.clipboard.writeText(msg.content)
                                  setCopiedMessageId(msg.id)
                                  setTimeout(() => setCopiedMessageId(null), 2000)
                                } catch (_) {}
                              }}
                            >
                              {copiedMessageId === msg.id ? (
                                <Check className="h-4 w-4 text-[#00A3EC]" />
                              ) : (
                                <Copy className="h-4 w-4" />
                              )}
                            </button>
                          </TooltipFlowbite>
                          <TooltipFlowbite content="Read aloud" position="top">
                            <button type="button" className="p-1.5 hover:bg-gray-100 hover:text-gray-600 rounded-md transition-colors" aria-label="Read aloud">
                              <Volume2 className="h-4 w-4" />
                            </button>
                          </TooltipFlowbite>
                          <TooltipFlowbite content="Reply to message" position="top">
                            <button
                              type="button"
                              className="p-1.5 hover:bg-gray-100 hover:text-gray-600 rounded-md transition-colors"
                              aria-label="Reply to message"
                              onClick={() => setReplyingTo({ id: msg.id, content: msg.content })}
                            >
                              <Reply className="h-4 w-4" />
                            </button>
                          </TooltipFlowbite>
                        </div>
                      </div>
                    )
                  )}
                  {isAssistantTyping && <LoadingMessage mentorName="agentAI" />}
                  <div ref={messagesEndRef} />
              </div>
                  );
                }
                return (
              <>
                <div className="w-full max-w-2xl mx-auto min-w-0 mt-0">
                  {/* Main Prompt */}
                  <h2 className="text-center text-base sm:text-lg md:text-xl font-medium mb-6 sm:mb-8 bg-gradient-to-r from-[#00A3EC] to-[#6988FF] bg-clip-text text-transparent px-1 mt-0">
                    Lets build together a great course!
                  </h2>

                  {/* Input Field */}
                  <div className="mb-4 min-w-0">
                    <div className="bg-[#FBFBFB] rounded-2xl flex flex-col border-2 relative min-w-0" style={{ borderColor: "#F1F2F3" }}>
                      {/* Selected attachments as chips */}
                      {selectedAttachments.length > 0 && (
                        <div className="flex items-center gap-2 px-4 pt-3 pb-1 overflow-x-auto flex-nowrap scrollbar-hide min-h-0 shrink-0">
                          {selectedAttachments.map((source) => (
                            <div
                              key={source.id}
                              className="relative flex items-center gap-2 rounded-md bg-gray-100/90 border border-gray-200/80 py-1.5 pl-2 pr-6 min-w-0 max-w-full shrink-0"
                            >
                              <FileImage className="h-4 w-4 shrink-0 text-[#2563EB]" />
                              <div className="flex flex-col min-w-0 text-left">
                                <span className="text-sm text-slate-700 truncate max-w-[140px] sm:max-w-[200px]" title={source.name}>
                                  {source.name}
                                </span>
                                <span className="text-xs text-slate-500">{source.type}</span>
                              </div>
                              <button
                                type="button"
                                onClick={() => setSelectedAttachments((prev) => prev.filter((s) => s.id !== source.id))}
                                className="absolute top-[-6px] right-[-6px] w-6 h-6 rounded-[5px] flex items-center justify-center text-slate-500 bg-white border border-gray-200/80 shadow-sm hover:bg-gray-100 hover:text-slate-700 transition-colors z-10"
                                aria-label="Remove attachment"
                              >
                                <X className="h-3.5 w-3.5" />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                      <Textarea
                      value={inputValue}
                      onChange={(e) => setInputValue(e.target.value)}
                      placeholder={isListening ? "" : "What's on your mind?"}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" && !e.shiftKey) {
                          e.preventDefault()
                          handleSubmit()
                        }
                      }}
                      className={cn(
                        "w-full bg-transparent px-4 text-base focus:outline-none rounded-2xl border-0 resize-none placeholder:text-gray-400 placeholder:text-base min-h-[80px] pb-3 shadow-none focus-visible:ring-0 focus-visible:border-0",
                        isListening ? "pt-10" : "pt-4",
                        selectedAttachments.length > 0 && "pt-1"
                      )}
                    />
                    {/* Listening indicator - top left */}
                    {isListening && (
                      <div className="absolute top-4 left-4 flex items-center gap-1 pointer-events-none">
                        {[0, 1, 2].map((i) => (
                          <div
                            key={i}
                            className="w-2 h-2 rounded-full animate-bounce"
                            style={{
                              backgroundColor: "#00A6F1",
                              animationDelay: `${i * 0.15}s`,
                            }}
                          />
                        ))}
                        <span className="ml-2 text-gray-500 text-sm">Listening...</span>
                      </div>
                    )}
                    {/* Bottom Row - Inside Input Buttons */}
                    <div className="flex items-center justify-between gap-2 px-3 sm:px-4 border-gray-200 rounded-b-2xl py-3 min-w-0">
                      <TooltipProvider>
                        <div className="flex items-center gap-1.5 flex-shrink-0">
                          <TooltipFlowbite content="Add Source" position="top">
                            <button
                              onClick={() => setIsAddSourcesDialogOpen(true)}
                              className="p-1.5 transition-colors"
                              style={{ color: "rgb(113,121,133)" }}
                              aria-label="Add attachment"
                            >
                              <Plus className="w-5 h-5" />
                            </button>
                          </TooltipFlowbite>
                          <input
                            ref={fileInputRef}
                            type="file"
                            className="hidden"
                            accept=".pdf,.doc,.docx,.txt,.md"
                            multiple
                          />
                        </div>
                        {/* Right Side Buttons */}
                        <div className="flex items-center gap-1.5 sm:gap-2 flex-shrink-0">
                          <TooltipFlowbite content={isListening ? "Stop listening" : "Dictate"} position="top">
                            <button
                              type="button"
                              onClick={handleDictationClick}
                              className={cn(
                                "w-9 h-9 flex items-center justify-center transition-colors rounded-lg",
                                isListening
                                  ? "text-white"
                                  : ""
                              )}
                              style={
                                isListening
                                  ? { backgroundColor: "#00A6F1", color: "white" }
                                  : { color: "rgb(113,121,133)" }
                              }
                              aria-label={isListening ? "Stop listening" : "Voice input"}
                            >
                              {isListening ? (
                                <Square className="w-3.5 h-3.5 fill-current" strokeWidth={0} />
                              ) : (
                                <Mic className="w-5 h-5" />
                              )}
                            </button>
                          </TooltipFlowbite>
                          {!isListening && (
                            <TooltipFlowbite content="Send Message" position="top">
                              <button
                                onClick={handleSubmit}
                                className="w-9 h-9 flex items-center justify-center rounded-lg transition-colors text-white hover:opacity-90"
                                style={{ backgroundColor: "#00A6F1" }}
                                aria-label="Submit"
                              >
                                <ArrowUp className="w-5 h-5" />
                              </button>
                            </TooltipFlowbite>
                          )}
                        </div>
                      </TooltipProvider>
                    </div>
                    </div>
                  </div>
                </div>

                {/* Jumpstart Templates */}
                <JumpstartTemplates onTemplateSelect={handleTemplateClick} />
              </>
                );
              })()
            ) : (
              /* Edit Course Details Form */
              <div className="rounded-lg border border-gray-200 p-4 sm:p-6 md:p-8 shadow-sm w-full max-w-full min-w-0" style={{ backgroundColor: "#F9FAFB" }}>
                <h2 className="text-lg sm:text-xl font-semibold mb-4 sm:mb-6" style={{ color: "rgb(113,121,133)" }}>
                  Edit Course Details
                </h2>

                <div className="space-y-4 sm:space-y-6">
                  {/* Display Name */}
                  <div className="space-y-2">
                    <Label htmlFor="display-name" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                      Display Name
                    </Label>
                    <div className="flex flex-col sm:flex-row gap-2">
                      <Input
                        id="display-name"
                        value={courseDetailsForm.displayName}
                        onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, displayName: e.target.value })}
                        className="flex-1 bg-white"
                      />
                      <Button
                        onClick={handleRegenerateDisplayName}
                        variant="outline"
                        className="px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50 whitespace-nowrap"
                        disabled={isRegenerating}
                      >
                        <RotateCw
                          className={cn("w-4 h-4 mr-2", isRegenerating && "animate-spin")}
                        />
                        Regenerate
                      </Button>
                    </div>
                    <p className="text-xs text-gray-500">Display name for the course</p>
                  </div>

                  {/* Date Fields – full width, aligned; single column on mobile, equal columns on sm+ */}
                  <div className="grid w-full grid-cols-1 gap-4 sm:grid-cols-2 sm:[grid-template-columns:minmax(0,1fr)_minmax(0,1fr)]">
                    {/* Start Date */}
                    <div className="flex min-w-0 w-full flex-col space-y-2 overflow-hidden">
                      <Label htmlFor="start-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Start Date
                      </Label>
                      <div className="date-picker-wrap relative w-full min-w-0 overflow-hidden">
                        <Input
                          id="start-date"
                          type="datetime-local"
                          value={courseDetailsForm.startDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, startDate: e.target.value })}
                          className="datetime-input bg-white min-w-0 w-full max-w-full"
                          placeholder="yyyy-mm-dd, --:-- --"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Course start date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>

                    {/* End Date */}
                    <div className="flex min-w-0 w-full flex-col space-y-2 overflow-hidden">
                      <Label htmlFor="end-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        End Date
                      </Label>
                      <div className="date-picker-wrap relative w-full min-w-0 overflow-hidden">
                        <Input
                          id="end-date"
                          type="datetime-local"
                          value={courseDetailsForm.endDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, endDate: e.target.value })}
                          className="datetime-input bg-white min-w-0 w-full max-w-full"
                          placeholder="yyyy-mm-dd, --:-- --"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Course end date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>

                    {/* Enrollment Start Date */}
                    <div className="flex min-w-0 w-full flex-col space-y-2 overflow-hidden">
                      <Label htmlFor="enrollment-start-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Enrollment Start Date
                      </Label>
                      <div className="date-picker-wrap relative w-full min-w-0 overflow-hidden">
                        <Input
                          id="enrollment-start-date"
                          type="datetime-local"
                          value={courseDetailsForm.enrollmentStartDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, enrollmentStartDate: e.target.value })}
                          className="datetime-input bg-white min-w-0 w-full max-w-full"
                          placeholder="yyyy-mm-dd, --:-- --"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Enrollment start date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>

                    {/* Enrollment End Date */}
                    <div className="flex min-w-0 w-full flex-col space-y-2 overflow-hidden">
                      <Label htmlFor="enrollment-end-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Enrollment End Date
                      </Label>
                      <div className="date-picker-wrap relative w-full min-w-0 overflow-hidden">
                        <Input
                          id="enrollment-end-date"
                          type="datetime-local"
                          value={courseDetailsForm.enrollmentEndDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, enrollmentEndDate: e.target.value })}
                          className="datetime-input bg-white min-w-0 w-full max-w-full"
                          placeholder="yyyy-mm-dd, --:-- --"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Enrollment end date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>
                  </div>

                  {/* Course Descriptions */}
                  <div className="space-y-3 sm:space-y-4 relative">
                    {isAutoGeneratingDescriptions && (
                      <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-10 rounded-lg flex items-center justify-center">
                        <div className="flex flex-col items-center justify-center space-y-4">
                          <div className="relative">
                            <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
                            <div className="absolute inset-0 flex items-center justify-center">
                              <Sparkles className="w-6 h-6 text-blue-600 animate-pulse" />
                            </div>
                          </div>
                          <p className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                            AI is generating course descriptions...
                          </p>
                        </div>
                      </div>
                    )}
                    <div>
                      <h3 className="text-base font-semibold mb-1" style={{ color: "rgb(113,121,133)" }}>
                        Course Descriptions
                      </h3>
                      <p className="text-xs text-gray-500">Add course descriptions (optional)</p>
                    </div>

                    {/* Description */}
                    <div className="space-y-2">
                      <Label htmlFor="description" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Description
                      </Label>
                      {/* Rich Text Editor Toolbar */}
                      <div className="flex items-center gap-1 p-2 border border-gray-200 rounded-t-lg bg-gray-50 overflow-x-auto flex-wrap sm:flex-nowrap">
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Bold">
                          <Bold className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Italic">
                          <Italic className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Link">
                          <LinkIcon className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Bullet List">
                          <List className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Numbered List">
                          <ListOrdered className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                      </div>
                      <div className="relative">
                        <Textarea
                          id="description"
                          value={courseDetailsForm.description}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, description: e.target.value })}
                          className="min-h-[200px] rounded-t-none border-t-0 bg-white"
                          placeholder="Enter course description..."
                          disabled={isAutoGeneratingDescriptions}
                        />
                        {isAutoGeneratingDescriptions && (
                          <div className="absolute inset-0 bg-gray-50/50 flex items-center justify-center rounded-b-lg">
                            <div className="flex items-center gap-2 text-sm text-gray-500">
                              <RotateCw className="w-4 h-4 animate-spin" />
                              <span>Generating description...</span>
                            </div>
                          </div>
                        )}
                      </div>
                      <Button
                        onClick={handleRegenerateDescription}
                        variant="outline"
                        size="sm"
                        className="mt-2 px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50"
                        disabled={isRegeneratingDescription || isAutoGeneratingDescriptions}
                      >
                        <RotateCw
                          className={cn("w-4 h-4 mr-2", isRegeneratingDescription && "animate-spin")}
                        />
                        Regenerate
                      </Button>
                    </div>

                    {/* Short Description */}
                    <div className="space-y-2">
                      <Label htmlFor="short-description" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Short Description
                      </Label>
                      <div className="relative">
                        <Textarea
                          id="short-description"
                          value={courseDetailsForm.shortDescription}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, shortDescription: e.target.value })}
                          className="min-h-[100px] bg-white"
                          placeholder="Enter short description..."
                          disabled={isAutoGeneratingDescriptions}
                        />
                        {isAutoGeneratingDescriptions && (
                          <div className="absolute inset-0 bg-gray-50/50 flex items-center justify-center rounded-lg">
                            <div className="flex items-center gap-2 text-sm text-gray-500">
                              <RotateCw className="w-4 h-4 animate-spin" />
                              <span>Generating short description...</span>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Course Image */}
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-base sm:text-lg font-semibold mb-1" style={{ color: "rgb(113,121,133)" }}>
                        Course Image
                      </h3>
                      <p className="text-xs text-gray-500">Upload or generate a course image (optional)</p>
                    </div>

                    <Tabs value={courseDetailsForm.imageTab} onValueChange={(value) => setCourseDetailsForm({ ...courseDetailsForm, imageTab: value as "upload" | "generate" })}>
                      <TabsList className="w-full sm:w-auto mb-4 sm:text-left sm:justify-start">
                        <TabsTrigger value="upload" className="flex-1 sm:flex-none">Upload Image</TabsTrigger>
                        <TabsTrigger value="generate" className="flex-1 sm:flex-none">Generate with AI</TabsTrigger>
                      </TabsList>
                      
                      <TabsContent value="upload" className="space-y-4">
                        <div className="space-y-2">
                          <Label className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                            Select Image File
                          </Label>
                          <div className="flex flex-col sm:flex-row gap-2 items-start">
                            <label className="cursor-pointer">
                              <Button variant="outline" type="button" className="px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50">
                                Choose File
                              </Button>
                              <input
                                type="file"
                                className="hidden"
                                accept="image/jpeg,image/png,image/gif"
                                onChange={handleImageUpload}
                              />
                            </label>
                            <span className="text-sm text-gray-500 self-center">
                              {courseDetailsForm.uploadedImageUrl ? "File selected" : "No file chosen"}
                            </span>
                          </div>
                          <p className="text-xs text-gray-500">Supported formats: JPG, PNG, GIF. Max size: 5MB</p>
                          {courseDetailsForm.uploadedImageUrl && (
                            <div className="mt-4">
                              <Label className="text-sm font-medium mb-2 block" style={{ color: "rgb(113,121,133)" }}>
                                Uploaded Image Preview
                              </Label>
                              <div className="border border-gray-200 rounded-lg p-4 bg-white">
                                <img
                                  src={courseDetailsForm.uploadedImageUrl}
                                  alt="Uploaded course image"
                                  className="w-full h-auto rounded-lg max-h-[400px] object-contain"
                                />
                              </div>
                            </div>
                          )}
                        </div>
                      </TabsContent>

                      <TabsContent value="generate" className="space-y-4">
                        {/* Image Description Prompt */}
                        <div className="space-y-2">
                          <Label className="text-sm font-semibold" style={{ color: "rgb(113,121,133)" }}>
                            Image Description Prompt
                          </Label>
                          <Textarea
                            value={courseDetailsForm.imageDescriptionPrompt}
                            onChange={(e) =>
                              setCourseDetailsForm({
                                ...courseDetailsForm,
                                imageDescriptionPrompt: e.target.value,
                              })
                            }
                            placeholder={courseDetailsForm.displayName || "Introduction to Typing: Improving Keyboard Skills"}
                            className="min-h-[120px] resize-y bg-white"
                          />
                          <p className="text-xs text-gray-500">
                            Describe the image you want to generate. Be specific about style, colors, and content.
                          </p>
                        </div>

                        {/* Generate Button */}
                        <Button
                          onClick={handleGenerateImage}
                          disabled={courseDetailsForm.isGeneratingImage || !courseDetailsForm.imageDescriptionPrompt.trim()}
                          className="px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {courseDetailsForm.isGeneratingImage ? (
                            <>
                              <RotateCw className="w-4 h-4 mr-2 animate-spin" />
                              Generating...
                            </>
                          ) : (
                            <>
                              <Sparkles className="w-4 h-4 mr-2" />
                              Generate Image with AI
                            </>
                          )}
                        </Button>

                        {/* Generated Image Preview */}
                        <div className="space-y-2">
                          <Label className="text-sm font-semibold" style={{ color: "rgb(113,121,133)" }}>
                            Generated Image Preview
                          </Label>
                          <div className="border border-gray-200 rounded-lg p-4 bg-white min-h-[300px] flex items-center justify-center">
                            {courseDetailsForm.isGeneratingImage ? (
                              <div className="flex flex-col items-center justify-center space-y-4">
                                <div className="relative">
                                  <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
                                  <div className="absolute inset-0 flex items-center justify-center">
                                    <Sparkles className="w-6 h-6 text-blue-600 animate-pulse" />
                                  </div>
                                </div>
                                <p className="text-sm text-gray-500">Generating image...</p>
                              </div>
                            ) : courseDetailsForm.generatedImageUrl ? (
                              <img
                                src={courseDetailsForm.generatedImageUrl}
                                alt="Generated course image"
                                className="w-full h-auto rounded-lg max-h-[400px] object-contain"
                                style={{
                                  animation: "fadeIn 0.5s ease-in",
                                }}
                              />
                            ) : (
                              <p className="text-sm text-gray-400">No image generated yet</p>
                            )}
                          </div>
                        </div>
                      </TabsContent>
                    </Tabs>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row justify-end gap-3 mt-8">
                  <Button
                    variant="outline"
                    onClick={handleBack}
                    className="w-full sm:w-auto px-6 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50"
                  >
                    <ArrowLeft className="w-4 h-4 mr-2" />
                    Back
                  </Button>
                  <Button
                    onClick={handleCreateCourse}
                    className="w-full sm:w-auto px-6 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90"
                  >
                    Create Course
                  </Button>
                </div>
              </div>
            )}
          </div>
            </div>

          </div>

            {/* Fixed prompt bar when in chat list view (same as chats page) */}
            {hasChatMessages && !showCourseForm && !isCreatingCourse && (
              <TooltipProvider>
                <div
                  className={cn(
                    "fixed right-0 left-0 z-40 bg-white/95 backdrop-blur px-3 sm:px-4 pt-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] transition-[left] duration-300",
                    sidebarCollapsed ? "md:left-16" : "md:left-64",
                  )}
                  style={{ borderColor: "#F1F2F3", bottom: inputBarBottom }}
                >
                  <div className="w-full max-w-3xl mx-auto min-w-0">
                    <ChatInputForm
                      value={inputValue}
                      onChange={setInputValue}
                      onSubmit={handleSubmit}
                      placeholder="Ask anything"
                      onAddSourcesClick={() => setIsAddSourcesDialogOpen(true)}
                      onVoiceClick={handleDictationClick}
                      isListening={isListening}
                      selectedAttachments={selectedAttachments}
                      onRemoveAttachment={(id) => setSelectedAttachments((prev) => prev.filter((s) => s.id !== id))}
                      replyingTo={replyingTo}
                      onClearReply={() => setReplyingTo(null)}
                      compact
                      fileInputRef={fileInputRef}
                    />
                  </div>
                </div>
              </TooltipProvider>
            )}

            {/* Footer */}
            <PlatformFooter />
        </main>
        </div>
      </div>

      {/* Add Sources Dialog */}
      <AddSourcesDialog
        open={isAddSourcesDialogOpen}
        onOpenChange={setIsAddSourcesDialogOpen}
        onFileInputTrigger={handleFileInputTrigger}
        onSourcesSelected={setSelectedAttachments}
      />
    </div>
  )
}
