"use client"

import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import { SidebarLearner } from "@/components/platform/sidebar-learner"
import { Header } from "@/components/platform/header"
import { PlatformFooter } from "@/components/platform/platform-footer"
import { Plus, Mic, ArrowUp, RotateCw, ArrowLeft, Calendar as CalendarIcon, Bold, Italic, Link as LinkIcon, List, ListOrdered, Upload, Sparkles, FileImage, X } from "lucide-react"
import { cn } from "@/lib/utils"
import { JumpstartTemplates } from "@/components/jumpstart-templates"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { AddSourcesDialog, type SelectedSource } from "@/components/chat-input/add-sources-dialog"
import ChatButton from "@/components/chat-button"
import { TooltipFlowbite, TooltipProvider } from "@/components/ui/tooltip-flowbite"

declare global {
  interface Window {
    SpeechRecognition: new () => any
    webkitSpeechRecognition: new () => any
  }
}

export default function HomePage() {
  const [inputValue, setInputValue] = useState("")
  const [isListening, setIsListening] = useState(false)
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [showCourseForm, setShowCourseForm] = useState(false)
  const [formStep, setFormStep] = useState<1 | 2>(1)
  const [isRegenerating, setIsRegenerating] = useState(false)
  const [isRegeneratingDescription, setIsRegeneratingDescription] = useState(false)
  const [isAutoGeneratingDescriptions, setIsAutoGeneratingDescriptions] = useState(false)
  const [hasAutoGeneratedDescriptions, setHasAutoGeneratedDescriptions] = useState(false)
  const [isAddSourcesDialogOpen, setIsAddSourcesDialogOpen] = useState(false)
  const [selectedAttachments, setSelectedAttachments] = useState<SelectedSource[]>([])
  const fileInputRef = useRef<HTMLInputElement>(null)
  const recognitionRef = useRef<any>(null)
  const [courseForm, setCourseForm] = useState({
    courseName: "",
    organization: "test_admin",
    courseNumber: "",
    courseRun: "",
  })
  const [courseDetailsForm, setCourseDetailsForm] = useState({
    displayName: "",
    startDate: "",
    endDate: "",
    enrollmentStartDate: "",
    enrollmentEndDate: "",
    description: "",
    shortDescription: "",
    imageTab: "upload" as "upload" | "generate",
    imageDescriptionPrompt: "",
    isGeneratingImage: false,
    generatedImageUrl: null as string | null,
    uploadedImageUrl: null as string | null,
  })
  const router = useRouter()

  const isLoggedIn = true

  // Cleanup speech recognition on unmount
  useEffect(() => {
    return () => {
      if (recognitionRef.current) {
        try {
          recognitionRef.current.stop()
        } catch (_) {}
        recognitionRef.current = null
      }
      setIsListening(false)
    }
  }, [])

  const stopDictation = () => {
    if (recognitionRef.current) {
      try {
        recognitionRef.current.stop()
      } catch (_) {}
      recognitionRef.current = null
    }
    setIsListening(false)
  }

  const handleDictationClick = () => {
    if (isListening) {
      stopDictation()
      return
    }

    const SpeechRecognition = typeof window !== "undefined" && (window.SpeechRecognition || window.webkitSpeechRecognition)
    if (!SpeechRecognition) {
      if (typeof window !== "undefined") {
        alert("Your browser does not support speech recognition. Please try Chrome or Edge.")
      }
      return
    }

    setIsListening(true)

    const recognition = new SpeechRecognition()
    recognition.continuous = true
    recognition.interimResults = true
    recognition.lang = "en-US"

    recognition.onresult = (event: any) => {
      let finalTranscript = ""
      for (let i = 0; i < event.results.length; i++) {
        finalTranscript += event.results[i][0].transcript
      }
      setInputValue(finalTranscript)
    }

    recognition.onerror = () => {
      stopDictation()
    }

    recognition.onend = () => {
      setIsListening(false)
      recognitionRef.current = null
    }

    try {
      recognition.start()
      recognitionRef.current = recognition
    } catch (_) {
      setIsListening(false)
    }
  }

  const handleSubmit = () => {
    if (inputValue.trim()) {
      // Generate course name from input
      const generatedCourseName = inputValue.trim()
      // Generate course number (first letters of words)
      const courseNumber = generatedCourseName
        .split(" ")
        .map((word) => word[0]?.toUpperCase() || "")
        .join("")
        .slice(0, 3)
      // Generate course run (current year and month)
      const now = new Date()
      const courseRun = `${now.getFullYear()}_${String(now.getMonth() + 1).padStart(2, "0")}`

      setCourseForm({
        courseName: generatedCourseName,
        organization: "test_admin",
        courseNumber: courseNumber,
        courseRun: courseRun,
      })
      setCourseDetailsForm((prev) => ({
        ...prev,
        displayName: generatedCourseName,
        description: `The ${generatedCourseName} course is designed to provide comprehensive learning on this topic. This course covers fundamental concepts and explores practical applications.`,
        shortDescription: `The ${generatedCourseName} course is designed to equip professionals with the knowledge and tools needed.`,
        imageDescriptionPrompt: generatedCourseName,
      }))
      setShowCourseForm(true)
      setFormStep(1)
    }
  }

  const handleRegenerate = () => {
    setIsRegenerating(true)
    setTimeout(() => {
      const generatedCourseName = inputValue.trim()
      setCourseForm((prev) => ({
        ...prev,
        courseName: generatedCourseName,
      }))
      setIsRegenerating(false)
    }, 1000)
  }

  const handleRegenerateDisplayName = () => {
    setIsRegenerating(true)
    setTimeout(() => {
      const generatedName = courseForm.courseName || inputValue.trim()
      setCourseDetailsForm((prev) => ({
        ...prev,
        displayName: generatedName,
      }))
      setIsRegenerating(false)
    }, 1000)
  }

  const handleRegenerateDescription = () => {
    setIsRegeneratingDescription(true)
    setTimeout(() => {
      const generatedDescription = `The ${courseForm.courseName || courseDetailsForm.displayName} course is designed to provide comprehensive learning on this topic. This course covers fundamental concepts and explores practical applications.`
      setCourseDetailsForm((prev) => ({
        ...prev,
        description: generatedDescription,
      }))
      setIsRegeneratingDescription(false)
    }, 1000)
  }

  const handleGenerateImage = () => {
    if (!courseDetailsForm.imageDescriptionPrompt.trim()) {
      return
    }
    setCourseDetailsForm((prev) => ({ ...prev, isGeneratingImage: true }))
    // Simulate image generation (replace with actual API call)
    setTimeout(() => {
      // In a real app, this would be the URL from the API response
      const mockImageUrl = `https://picsum.photos/800/600?random=${Date.now()}`
      setCourseDetailsForm((prev) => ({
        ...prev,
        isGeneratingImage: false,
        generatedImageUrl: mockImageUrl,
      }))
    }, 3000) // 3 second animation
  }

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onloadend = () => {
        setCourseDetailsForm((prev) => ({
          ...prev,
          uploadedImageUrl: reader.result as string,
        }))
      }
      reader.readAsDataURL(file)
    }
  }

  const handleFileInputTrigger = () => {
    fileInputRef.current?.click()
  }

  const handleBack = () => {
    if (formStep === 2) {
      setFormStep(1)
    } else {
      setShowCourseForm(false)
      setInputValue("")
    }
  }

  const handleNext = () => {
    if (formStep === 1) {
      setFormStep(2)
    }
  }

  // Auto-generate descriptions when step 2 loads
  useEffect(() => {
    if (formStep === 2 && !hasAutoGeneratedDescriptions && !courseDetailsForm.description && !courseDetailsForm.shortDescription) {
      setIsAutoGeneratingDescriptions(true)
      setHasAutoGeneratedDescriptions(true)
      // Simulate AI generation with a delay
      setTimeout(() => {
        const courseName = courseForm.courseName || courseDetailsForm.displayName || "this course"
        const generatedDescription = `The ${courseName} course is designed to provide comprehensive learning on this topic. This course covers fundamental concepts, explores practical applications, and equips learners with the knowledge and skills needed to excel. Through interactive lessons, hands-on exercises, and real-world examples, students will gain a deep understanding of the subject matter and be prepared to apply their learning in professional settings.`
        const generatedShortDescription = `The ${courseName} course is designed to equip professionals with the knowledge and tools needed to succeed.`
        
        setCourseDetailsForm((prev) => ({
          ...prev,
          description: generatedDescription,
          shortDescription: generatedShortDescription,
        }))
        setIsAutoGeneratingDescriptions(false)
      }, 2000) // 2 second generation animation
    }
  }, [formStep, hasAutoGeneratedDescriptions, courseDetailsForm.description, courseDetailsForm.shortDescription, courseForm.courseName, courseDetailsForm.displayName])

  const handleCreateCourse = () => {
    console.log("Create course with:", { ...courseForm, ...courseDetailsForm })
    // Handle course creation
  }

  const handleTemplateClick = (template: string) => {
    setInputValue(template)
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Sidebar */}
      <SidebarLearner
        isCollapsed={sidebarCollapsed}
        onToggleCollapse={() => setSidebarCollapsed(!sidebarCollapsed)}
        isMobileOpen={mobileMenuOpen}
        onMobileClose={() => setMobileMenuOpen(false)}
        showAdminButtons={true}
        isLoggedIn={isLoggedIn}
      />

      {/* Main Content Area */}
      <div
        className={cn(
          "flex flex-col min-h-screen transition-all duration-300",
          sidebarCollapsed ? "md:ml-16" : "md:ml-64",
        )}
      >
        {/* Header */}
        <Header
          onMobileMenuToggle={() => setMobileMenuOpen(true)}
          isLoggedIn={isLoggedIn}
          showLogo={true}
          showBackButton={true}
          showModelSelector={true}
        />

          {/* Main Content */}
        <main className="flex-1 flex flex-col transition-all duration-300 overflow-y-auto">
          <div className="flex flex-1">
            <div className="flex-1 flex items-center justify-center px-5 sm:px-2 py-8 sm:py-12 pb-[200px] md:pb-[200px] w-full sm:pl-8 sm:pr-8 md:pr-20">
          <div className="w-full max-w-6xl">
            {!showCourseForm ? (
              <>
                <div className="w-full max-w-2xl mx-auto">
                  {/* Main Prompt */}
                  <h2 className="text-center text-lg md:text-xl font-medium mb-8 bg-gradient-to-r from-[#00A3EC] to-[#6988FF] bg-clip-text text-transparent">
                    Lets build together a great course!
                  </h2>

                  {/* Input Field */}
                  <div className="mb-4">
                    <div className="bg-[#FBFBFB] rounded-2xl flex flex-col border-2 relative" style={{ borderColor: "#F1F2F3" }}>
                      {/* Selected attachments as chips */}
                      {selectedAttachments.length > 0 && (
                        <div className="flex flex-wrap items-center gap-2 px-4 pt-3 pb-1">
                          {selectedAttachments.map((source) => (
                            <div
                              key={source.id}
                              className="flex items-center gap-2 rounded-md bg-gray-100/90 border border-gray-200/80 py-1.5 pl-2 pr-1 min-w-0 max-w-full"
                            >
                              <FileImage className="h-4 w-4 shrink-0 text-[#2563EB]" />
                              <div className="flex flex-col min-w-0 text-left">
                                <span className="text-sm text-slate-700 truncate max-w-[140px] sm:max-w-[200px]" title={source.name}>
                                  {source.name}
                                </span>
                                <span className="text-xs text-slate-500">{source.type}</span>
                              </div>
                              <button
                                type="button"
                                onClick={() => setSelectedAttachments((prev) => prev.filter((s) => s.id !== source.id))}
                                className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-slate-500 hover:bg-gray-300/80 hover:text-slate-700 transition-colors"
                                aria-label="Remove attachment"
                              >
                                <X className="h-3.5 w-3.5" />
                              </button>
                            </div>
                          ))}
                        </div>
                      )}
                      <Textarea
                      value={inputValue}
                      onChange={(e) => setInputValue(e.target.value)}
                      placeholder={isListening ? "" : "What's on your mind?"}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" && !e.shiftKey) {
                          e.preventDefault()
                          handleSubmit()
                        }
                      }}
                      className={cn(
                        "w-full bg-transparent px-4 text-base focus:outline-none rounded-2xl border-0 resize-none placeholder:text-gray-400 placeholder:text-base min-h-[80px] pb-3 shadow-none focus-visible:ring-0 focus-visible:border-0",
                        isListening ? "pt-10" : "pt-4",
                        selectedAttachments.length > 0 && "pt-1"
                      )}
                    />
                    {/* Listening indicator - top left */}
                    {isListening && (
                      <div className="absolute top-4 left-4 flex items-center gap-1 pointer-events-none">
                        {[0, 1, 2].map((i) => (
                          <div
                            key={i}
                            className="w-2 h-2 rounded-full animate-bounce"
                            style={{
                              backgroundColor: "#00A6F1",
                              animationDelay: `${i * 0.15}s`,
                            }}
                          />
                        ))}
                        <span className="ml-2 text-gray-500 text-sm">Listening...</span>
                      </div>
                    )}
                    {/* Bottom Row - Inside Input Buttons */}
                    <div className="flex items-center justify-between px-4 border-gray-200 rounded-b-2xl py-3">
                      <TooltipProvider>
                        <div className="flex items-center gap-1.5">
                          <TooltipFlowbite content="Add Source" position="top">
                            <button
                              onClick={() => setIsAddSourcesDialogOpen(true)}
                              className="p-1.5 transition-colors"
                              style={{ color: "rgb(113,121,133)" }}
                              aria-label="Add attachment"
                            >
                              <Plus className="w-5 h-5" />
                            </button>
                          </TooltipFlowbite>
                          <input
                            ref={fileInputRef}
                            type="file"
                            className="hidden"
                            accept=".pdf,.doc,.docx,.txt,.md"
                            multiple
                          />
                        </div>
                        {/* Right Side Buttons */}
                        <div className="flex items-center gap-2">
                          <TooltipFlowbite content="Dictate" position="top">
                            <button
                              type="button"
                              onClick={handleDictationClick}
                              className={cn(
                                "p-1.5 transition-colors rounded-lg",
                                isListening
                                  ? "text-white"
                                  : ""
                              )}
                              style={
                                isListening
                                  ? { backgroundColor: "#00A6F1", color: "white" }
                                  : { color: "rgb(113,121,133)" }
                              }
                              aria-label="Voice input"
                            >
                              <Mic className="w-5 h-5" />
                            </button>
                          </TooltipFlowbite>
                          <TooltipFlowbite content="Send Message" position="top">
                            <button
                              onClick={handleSubmit}
                              className="w-9 h-9 flex items-center justify-center rounded-lg transition-colors text-white hover:opacity-90"
                              style={{ backgroundColor: "#00A6F1" }}
                              aria-label="Submit"
                            >
                              <ArrowUp className="w-5 h-5" />
                            </button>
                          </TooltipFlowbite>
                        </div>
                      </TooltipProvider>
                    </div>
                    </div>
                  </div>
                </div>

                {/* Jumpstart Templates */}
                <JumpstartTemplates onTemplateSelect={handleTemplateClick} />
              </>
            ) : formStep === 1 ? (
              /* Step 1: Course Creation Form */
              <div className="rounded-lg border border-gray-200 p-4 sm:p-6 md:p-8 shadow-sm w-full" style={{ backgroundColor: "#F9FAFB" }}>
                <h2 className="text-lg sm:text-xl font-semibold mb-4 sm:mb-6" style={{ color: "rgb(113,121,133)" }}>
                  Create a new course
                </h2>

                <div className="space-y-4 sm:space-y-6">
                  {/* Course name */}
                  <div className="space-y-2">
                    <Label htmlFor="course-name" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                      Course name
                    </Label>
                    <div className="flex flex-col sm:flex-row gap-2">
                      <Input
                        id="course-name"
                        value={courseForm.courseName}
                        onChange={(e) => setCourseForm({ ...courseForm, courseName: e.target.value })}
                        className="flex-1"
                      />
                      <Button
                        onClick={handleRegenerate}
                        variant="outline"
                        className="px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50 whitespace-nowrap"
                        disabled={isRegenerating}
                      >
                        <RotateCw
                          className={cn("w-4 h-4 mr-2", isRegenerating && "animate-spin")}
                        />
                        Regenerate
                      </Button>
                    </div>
                    <p className="text-xs text-gray-500">
                      The public display name for your course. This cannot be changed, but you can set a different display name in advanced settings later.
                    </p>
                  </div>

                  {/* Organization */}
                  <div className="space-y-2">
                    <Label htmlFor="organization" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                      Organization
                    </Label>
                    <Input
                      id="organization"
                      value={courseForm.organization}
                      disabled
                      className="bg-gray-100 cursor-not-allowed"
                    />
                    <p className="text-xs text-gray-500">
                      Note: The organization is automatically set to your username and cannot be changed. This is part of the course URL.
                    </p>
                  </div>

                  {/* Course number */}
                  <div className="space-y-2">
                    <Label htmlFor="course-number" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                      Course number
                    </Label>
                    <Input
                      id="course-number"
                      value={courseForm.courseNumber}
                      onChange={(e) => setCourseForm({ ...courseForm, courseNumber: e.target.value })}
                      className="uppercase"
                    />
                    <p className="text-xs text-gray-500">
                      Note: This is part of your course URL, so no spaces or special characters are allowed and it cannot be changed.
                    </p>
                  </div>

                  {/* Course run */}
                  <div className="space-y-2">
                    <Label htmlFor="course-run" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                      Course run
                    </Label>
                    <Input
                      id="course-run"
                      value={courseForm.courseRun}
                      onChange={(e) => setCourseForm({ ...courseForm, courseRun: e.target.value })}
                    />
                    <p className="text-xs text-gray-500">
                      Note: This is part of your course URL, so no spaces or special characters are allowed and it cannot be changed.
                    </p>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row justify-end gap-3 mt-6 sm:mt-8">
                  <Button
                    variant="outline"
                    onClick={handleBack}
                    className="w-full sm:w-auto px-6 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50"
                  >
                    <ArrowLeft className="w-4 h-4 mr-2" />
                    Back
                  </Button>
                  <Button
                    onClick={handleNext}
                    className="w-full sm:w-auto px-6 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90"
                  >
                    Next
                  </Button>
                </div>
              </div>
            ) : (
              /* Step 2: Edit Course Details Form */
              <div className="rounded-lg border border-gray-200 p-4 sm:p-6 md:p-8 shadow-sm w-full" style={{ backgroundColor: "#F9FAFB" }}>
                <h2 className="text-lg sm:text-xl font-semibold mb-4 sm:mb-6" style={{ color: "rgb(113,121,133)" }}>
                  Edit Course Details
                </h2>

                <div className="space-y-4 sm:space-y-6">
                  {/* Display Name */}
                  <div className="space-y-2">
                    <Label htmlFor="display-name" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                      Display Name
                    </Label>
                    <div className="flex flex-col sm:flex-row gap-2">
                      <Input
                        id="display-name"
                        value={courseDetailsForm.displayName}
                        onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, displayName: e.target.value })}
                        className="flex-1"
                      />
                      <Button
                        onClick={handleRegenerateDisplayName}
                        variant="outline"
                        className="px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50 whitespace-nowrap"
                        disabled={isRegenerating}
                      >
                        <RotateCw
                          className={cn("w-4 h-4 mr-2", isRegenerating && "animate-spin")}
                        />
                        Regenerate
                      </Button>
                    </div>
                    <p className="text-xs text-gray-500">Display name for the course</p>
                  </div>

                  {/* Date Fields */}
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {/* Start Date */}
                    <div className="space-y-2">
                      <Label htmlFor="start-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Start Date
                      </Label>
                      <div className="relative">
                        <CalendarIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none z-10" />
                        <Input
                          id="start-date"
                          type="datetime-local"
                          value={courseDetailsForm.startDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, startDate: e.target.value })}
                          className="pl-10"
                          placeholder="yyyy-mm-dd, --:----"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Course start date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>

                    {/* End Date */}
                    <div className="space-y-2">
                      <Label htmlFor="end-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        End Date
                      </Label>
                      <div className="relative">
                        <CalendarIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none z-10" />
                        <Input
                          id="end-date"
                          type="datetime-local"
                          value={courseDetailsForm.endDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, endDate: e.target.value })}
                          className="pl-10"
                          placeholder="yyyy-mm-dd, --:----"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Course end date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>

                    {/* Enrollment Start Date */}
                    <div className="space-y-2">
                      <Label htmlFor="enrollment-start-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Enrollment Start Date
                      </Label>
                      <div className="relative">
                        <CalendarIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none z-10" />
                        <Input
                          id="enrollment-start-date"
                          type="datetime-local"
                          value={courseDetailsForm.enrollmentStartDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, enrollmentStartDate: e.target.value })}
                          className="pl-10"
                          placeholder="yyyy-mm-dd, --:----"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Enrollment start date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>

                    {/* Enrollment End Date */}
                    <div className="space-y-2">
                      <Label htmlFor="enrollment-end-date" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Enrollment End Date
                      </Label>
                      <div className="relative">
                        <CalendarIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400 pointer-events-none z-10" />
                        <Input
                          id="enrollment-end-date"
                          type="datetime-local"
                          value={courseDetailsForm.enrollmentEndDate}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, enrollmentEndDate: e.target.value })}
                          className="pl-10"
                          placeholder="yyyy-mm-dd, --:----"
                        />
                      </div>
                      <p className="text-xs text-gray-500">Enrollment end date and time (optional, format: YYYY-MM-DDTHH:mm)</p>
                    </div>
                  </div>

                  {/* Course Descriptions */}
                  <div className="space-y-3 sm:space-y-4 relative">
                    {isAutoGeneratingDescriptions && (
                      <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-10 rounded-lg flex items-center justify-center">
                        <div className="flex flex-col items-center justify-center space-y-4">
                          <div className="relative">
                            <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
                            <div className="absolute inset-0 flex items-center justify-center">
                              <Sparkles className="w-6 h-6 text-blue-600 animate-pulse" />
                            </div>
                          </div>
                          <p className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                            AI is generating course descriptions...
                          </p>
                        </div>
                      </div>
                    )}
                    <div>
                      <h3 className="text-base font-semibold mb-1" style={{ color: "rgb(113,121,133)" }}>
                        Course Descriptions
                      </h3>
                      <p className="text-xs text-gray-500">Add course descriptions (optional)</p>
                    </div>

                    {/* Description */}
                    <div className="space-y-2">
                      <Label htmlFor="description" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Description
                      </Label>
                      {/* Rich Text Editor Toolbar */}
                      <div className="flex items-center gap-1 p-2 border border-gray-200 rounded-t-lg bg-gray-50">
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Bold">
                          <Bold className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Italic">
                          <Italic className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Link">
                          <LinkIcon className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Bullet List">
                          <List className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                        <button className="p-1.5 hover:bg-gray-200 rounded" title="Numbered List">
                          <ListOrdered className="w-4 h-4" style={{ color: "rgb(113,121,133)" }} />
                        </button>
                      </div>
                      <div className="relative">
                        <Textarea
                          id="description"
                          value={courseDetailsForm.description}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, description: e.target.value })}
                          className="min-h-[200px] rounded-t-none border-t-0"
                          placeholder="Enter course description..."
                          disabled={isAutoGeneratingDescriptions}
                        />
                        {isAutoGeneratingDescriptions && (
                          <div className="absolute inset-0 bg-gray-50/50 flex items-center justify-center rounded-b-lg">
                            <div className="flex items-center gap-2 text-sm text-gray-500">
                              <RotateCw className="w-4 h-4 animate-spin" />
                              <span>Generating description...</span>
                            </div>
                          </div>
                        )}
                      </div>
                      <Button
                        onClick={handleRegenerateDescription}
                        variant="outline"
                        size="sm"
                        className="mt-2 px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50"
                        disabled={isRegeneratingDescription || isAutoGeneratingDescriptions}
                      >
                        <RotateCw
                          className={cn("w-4 h-4 mr-2", isRegeneratingDescription && "animate-spin")}
                        />
                        Regenerate
                      </Button>
                    </div>

                    {/* Short Description */}
                    <div className="space-y-2">
                      <Label htmlFor="short-description" className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                        Short Description
                      </Label>
                      <div className="relative">
                        <Textarea
                          id="short-description"
                          value={courseDetailsForm.shortDescription}
                          onChange={(e) => setCourseDetailsForm({ ...courseDetailsForm, shortDescription: e.target.value })}
                          className="min-h-[100px]"
                          placeholder="Enter short description..."
                          disabled={isAutoGeneratingDescriptions}
                        />
                        {isAutoGeneratingDescriptions && (
                          <div className="absolute inset-0 bg-gray-50/50 flex items-center justify-center rounded-lg">
                            <div className="flex items-center gap-2 text-sm text-gray-500">
                              <RotateCw className="w-4 h-4 animate-spin" />
                              <span>Generating short description...</span>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Course Image */}
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-base sm:text-lg font-semibold mb-1" style={{ color: "rgb(113,121,133)" }}>
                        Course Image
                      </h3>
                      <p className="text-xs text-gray-500">Upload or generate a course image (optional)</p>
                    </div>

                    <Tabs value={courseDetailsForm.imageTab} onValueChange={(value) => setCourseDetailsForm({ ...courseDetailsForm, imageTab: value as "upload" | "generate" })}>
                      <TabsList className="w-full sm:w-auto mb-4 sm:text-left sm:justify-start">
                        <TabsTrigger value="upload" className="flex-1 sm:flex-none">Upload Image</TabsTrigger>
                        <TabsTrigger value="generate" className="flex-1 sm:flex-none">Generate with AI</TabsTrigger>
                      </TabsList>
                      
                      <TabsContent value="upload" className="space-y-4">
                        <div className="space-y-2">
                          <Label className="text-sm font-medium" style={{ color: "rgb(113,121,133)" }}>
                            Select Image File
                          </Label>
                          <div className="flex flex-col sm:flex-row gap-2 items-start">
                            <label className="cursor-pointer">
                              <Button variant="outline" type="button" className="px-4 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50">
                                Choose File
                              </Button>
                              <input
                                type="file"
                                className="hidden"
                                accept="image/jpeg,image/png,image/gif"
                                onChange={handleImageUpload}
                              />
                            </label>
                            <span className="text-sm text-gray-500 self-center">
                              {courseDetailsForm.uploadedImageUrl ? "File selected" : "No file chosen"}
                            </span>
                          </div>
                          <p className="text-xs text-gray-500">Supported formats: JPG, PNG, GIF. Max size: 5MB</p>
                          {courseDetailsForm.uploadedImageUrl && (
                            <div className="mt-4">
                              <Label className="text-sm font-medium mb-2 block" style={{ color: "rgb(113,121,133)" }}>
                                Uploaded Image Preview
                              </Label>
                              <div className="border border-gray-200 rounded-lg p-4 bg-white">
                                <img
                                  src={courseDetailsForm.uploadedImageUrl}
                                  alt="Uploaded course image"
                                  className="w-full h-auto rounded-lg max-h-[400px] object-contain"
                                />
                              </div>
                            </div>
                          )}
                        </div>
                      </TabsContent>

                      <TabsContent value="generate" className="space-y-4">
                        {/* Image Description Prompt */}
                        <div className="space-y-2">
                          <Label className="text-sm font-semibold" style={{ color: "rgb(113,121,133)" }}>
                            Image Description Prompt
                          </Label>
                          <Textarea
                            value={courseDetailsForm.imageDescriptionPrompt}
                            onChange={(e) =>
                              setCourseDetailsForm({
                                ...courseDetailsForm,
                                imageDescriptionPrompt: e.target.value,
                              })
                            }
                            placeholder={courseDetailsForm.displayName || "Introduction to Typing: Improving Keyboard Skills"}
                            className="min-h-[120px] resize-y"
                          />
                          <p className="text-xs text-gray-500">
                            Describe the image you want to generate. Be specific about style, colors, and content.
                          </p>
                        </div>

                        {/* Generate Button */}
                        <Button
                          onClick={handleGenerateImage}
                          disabled={courseDetailsForm.isGeneratingImage || !courseDetailsForm.imageDescriptionPrompt.trim()}
                          className="px-4 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {courseDetailsForm.isGeneratingImage ? (
                            <>
                              <RotateCw className="w-4 h-4 mr-2 animate-spin" />
                              Generating...
                            </>
                          ) : (
                            <>
                              <Sparkles className="w-4 h-4 mr-2" />
                              Generate Image with AI
                            </>
                          )}
                        </Button>

                        {/* Generated Image Preview */}
                        <div className="space-y-2">
                          <Label className="text-sm font-semibold" style={{ color: "rgb(113,121,133)" }}>
                            Generated Image Preview
                          </Label>
                          <div className="border border-gray-200 rounded-lg p-4 bg-white min-h-[300px] flex items-center justify-center">
                            {courseDetailsForm.isGeneratingImage ? (
                              <div className="flex flex-col items-center justify-center space-y-4">
                                <div className="relative">
                                  <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
                                  <div className="absolute inset-0 flex items-center justify-center">
                                    <Sparkles className="w-6 h-6 text-blue-600 animate-pulse" />
                                  </div>
                                </div>
                                <p className="text-sm text-gray-500">Generating image...</p>
                              </div>
                            ) : courseDetailsForm.generatedImageUrl ? (
                              <img
                                src={courseDetailsForm.generatedImageUrl}
                                alt="Generated course image"
                                className="w-full h-auto rounded-lg max-h-[400px] object-contain"
                                style={{
                                  animation: "fadeIn 0.5s ease-in",
                                }}
                              />
                            ) : (
                              <p className="text-sm text-gray-400">No image generated yet</p>
                            )}
                          </div>
                        </div>
                      </TabsContent>
                    </Tabs>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row justify-end gap-3 mt-8">
                  <Button
                    variant="outline"
                    onClick={handleBack}
                    className="w-full sm:w-auto px-6 py-2 text-sm font-medium border-gray-300 text-gray-700 hover:bg-gray-50"
                  >
                    <ArrowLeft className="w-4 h-4 mr-2" />
                    Back
                  </Button>
                  <Button
                    onClick={handleCreateCourse}
                    className="w-full sm:w-auto px-6 py-2 text-sm font-medium text-white bg-gradient-to-r from-[#00A3EC] to-[#6988FF] hover:opacity-90"
                  >
                    Create Course
                  </Button>
                </div>
              </div>
            )}
          </div>
            </div>

            {/* Chat Button - sticky right side */}
            <div className="hidden md:flex fixed top-20 right-0 z-[100]">
              <ChatButton />
            </div>
          </div>
        </main>

        {/* Footer */}
        <PlatformFooter />
      </div>

      {/* Add Sources Dialog */}
      <AddSourcesDialog
        open={isAddSourcesDialogOpen}
        onOpenChange={setIsAddSourcesDialogOpen}
        onFileInputTrigger={handleFileInputTrigger}
        onSourcesSelected={setSelectedAttachments}
      />
    </div>
  )
}
