export const skills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "Java",
  "C++",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "Vue.js",
  "Angular",
  "Express.js",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "Git",
  "GitHub",
  "GitLab",
  "CI/CD",
  "Jest",
  "Cypress",
  "Figma",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "UI/UX Design",
  "Responsive Design",
  "Mobile Development",
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "PHP",
  "Laravel",
  "Django",
  "Flask",
  "Ruby",
  "Ruby on Rails",
  "Go",
  "Rust",
  "C#",
  ".NET",
  "GraphQL",
  "REST APIs",
  "Microservices",
  "DevOps",
  "Linux",
  "Bash",
  "PowerShell",
  "Terraform",
  "Ansible",
  "Jenkins",
  "Machine Learning",
  "AI",
  "Data Science",
  "Pandas",
  "NumPy",
  "TensorFlow",
  "PyTorch",
  "Blockchain",
  "Solidity",
  "Web3",
  "Ethereum",
  "Smart Contracts",
  "Agile",
  "Scrum",
  "Kanban",
  "Project Management",
  "Team Leadership",
  "Communication",
  "Problem Solving",
]

export const RATING_LEVELS = {
  1: "BEGINNER",
  2: "NOVICE",
  3: "INTERMEDIATE",
  4: "ADVANCED",
  5: "EXPERT",
}

export const roles = [
  { title: "Software Developer", description: "Build and maintain software applications" },
  { title: "Frontend Developer", description: "Create user interfaces and experiences" },
  { title: "Backend Developer", description: "Develop server-side logic and APIs" },
  { title: "Full Stack Developer", description: "Work on both frontend and backend" },
  { title: "DevOps Engineer", description: "Manage infrastructure and deployments" },
  { title: "Data Scientist", description: "Analyze and interpret complex data" },
  { title: "Machine Learning Engineer", description: "Build ML models and systems" },
  { title: "Product Manager", description: "Define and prioritize product features" },
  { title: "UX Designer", description: "Design user experiences and flows" },
  { title: "UI Designer", description: "Create visual designs and interfaces" },
  { title: "Project Manager", description: "Coordinate and manage projects" },
  { title: "Technical Lead", description: "Guide technical decisions and teams" },
  { title: "Engineering Manager", description: "Lead and mentor engineering teams" },
  { title: "QA Engineer", description: "Ensure software quality and testing" },
  { title: "Security Engineer", description: "Protect systems and data" },
]
